### ISSUE TITLE
Error while installing via nuget(Install-Package Plaid )

### ISSUE THREAD

**Issue by rakeshbimra** [tmarkovski/plaid-net#1]
We are getting following error while installing Plaid nuget package from("https://www.nuget.org/packages/Plaid"). 

Install failed. Rolling back...
Install-Package : Could not install package 'Plaid 1.0.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or
 content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ install-package <<<<  plaid
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
PM>

**Comment by tmarkovski** [comment]
Hi @rakeshbimra 
The package version you just attempted (1.0.4) targets .NET 4.5.2. I have uploaded a new version just now that targets 4.5. It should be up on NuGet. Just make sure it's version 1.0.5.

**Comment by rakeshbimra** [comment]
Thanks @tmarkovski . Now its working with .Net 4.5.2 framework
