### ISSUE TITLE
Empty result when call  GetUser

### ISSUE THREAD

**Issue by rakeshbimra** [tmarkovski/plaid-net#2]
We have getting empty result when we call GetUser method. see the following screen shot.

![get-user-plaid](https://cloud.githubusercontent.com/assets/16551629/12228441/90e66194-b861-11e5-82bd-5ace1a956bed.png)

Please suggest us how we can call API methods with ASP.NET MVC 5.0

**Comment by tmarkovski** [comment]
All of the methods use the async capabilities, you need to "await" your methods.
In your case, you can try this:
````csharp
var result = plaidServiceProvider.GetUser(accessToken);
result.Wait();
return result.Result;
````
or you can rewrite your entire method like this
````csharp
public async Task<ActionOutput> GetUser(string accessToken)
{
  var result = await plaidServiceProvider(accessToken);
  return result;
}
````

Check out this link for more information on asynchronous programming in .NET.
https://msdn.microsoft.com/en-us/library/hh191443(v=vs.140).aspx

**Comment by rakeshbimra** [comment]
thanks for your support @tmarkovski

**Comment by tmarkovski** [comment]
Glad I can help @rakeshbimra

**Comment by rakeshbimra** [comment]
hi @tmarkovski  could you please give your mail address?, we need some support regarding plaid implementation.

**Comment by tmarkovski** [comment]
This looks like it's Plaid API related error. I do not work for Plaid, so I can only help you with the Plaid .NET bindings. For what it's worth, I've seen this error happening often, and usually the issue resolves itself.
I would also suggest that you blur out your screenshots, as you have your client id and secret publicly posted.

**Comment by rakeshbimra** [comment]
Hi @tmarkovski, see the following steps how are trying to call PLAID API
1. First we authenticate with Plaid Link. it returns public_token after successfull athentication.
2. After that we are using this public_token to call "GetBalance" API.
3. But when we call "GetBalance" API as defined following, it starts endless processing.

  public class PlaidServiceProvider : IPlaidServiceProvider
    {
        private readonly IPlaidUserClient _userClient;
      
        public PlaidServiceProvider()
        {
            _userClient = new UsreCorpPlaidUserClient();
            
        }
       
        public async Task<User> GetUser(string accessToken)
        {
            try
            {
                var response = _userClient.GetBalance(accessToken);
                response.Wait();
                return response.Result;
            }
            catch (PlaidException ex)
            {
                throw ex;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

    }

**Comment by tmarkovski** [comment]
The public token you are getting from that service is not the same as access token needed by GetBalance endpoint. I believe you need to use the exchange token endpoint by passing the public token, which will return access token. You then use that access token to call the balance endpoint.

**Comment by rakeshbimra** [comment]
Hi @tmarkovski 
exchange token endpoint needs two parameters- public_token and accountId. We have public_token, because plaid link returns  public_token, but from where we will get accountId. Please suggest.
